### ISSUE TITLE
Doesn't acknowledge force verify command in any channel

### ISSUE THREAD

**Issue by sttephen** [learnspigot/discord-bot#10]
### Explain the issue.

.

**Comment by Nuckerr** [comment]
By doesn't acknowledge do you mean it doesn't give the role or send a welcome message?

**Comment by sttephen** [comment]
@Nuckerr both

**Comment by Nuckerr** [comment]
Good, thats what I'm getting :D

**Comment by Nuckerr** [comment]
(not that its good that its broken tho)

**Comment by sttephen** [comment]
:D
