### ISSUE TITLE
Add steps to make sure no double prompt showing

### ISSUE THREAD

**Issue by sttephen** [learnspigot/discord-bot#105]
We have a problem that happens quite frequently where the user & a staff member (or god forbit, multiple) will all run /close when they see the ticket coming to a natural end.

This causes a lot of issues. Among confusion, can lead to double rep and so on.

My solution is that when /close is run it will delete all above prompts so as to not confuse everyone.

**Comment by Nuckerr** [comment]
not sure if deleting the prompts will fix all this. This should already be accounted for tho. I'll recheck though

**Comment by Pan-nav** [comment]
> not sure if deleting the prompts will fix all this. This should already be accounted for tho. I'll recheck though

We tried deleting the messages twice, and it did actually work. Only 1 rep was added

**Comment by Pan-nav** [comment]
I am wanting to work on this but it doesn't let me! ;-;

**Comment by sttephen** [comment]
Fixed in 3.0.
