### ISSUE TITLE
Alert in #support for rep rewarded on tutorials/projects

### ISSUE THREAD

**Issue by joshdevous** [learnspigot/discord-bot#114]
### Explain your idea.

Currently reputation alerts only show up in support when from a ticket, I think it should also show up for the newer way of also getting rep, through creating useful tutorials and projects.

I’m not too sure for the design of this, maybe just modify the add rep command to have optional booleans to dictate whether the rep is being awarded for a tutorial or project, and use those to trigger alerts? I believe there’s also an action for right clicking a user to add rep there? If there’s any sort of checkbox item for the modal that would be cool.

**Comment by sttephen** [comment]
Overlaps slightly with #76.

We will need to redesign some things to note that they are from a tutorial.

To be honest, giving rep via context menu does not actually work when I tested it (can't test now as bot is down) and /managerep add does not take an integer amount so there is no way to give bulk rep atm.

I have just been running the command as many times as need be to assign rep. Sub-par, obviously, but hopefully someone will pick up my/your issue.

**Comment by joshdevous** [comment]
Gotcha, missed this issue. I'd agree to close this and I'll just add the alert suggestion as part of 76
