### ISSUE TITLE
Change #suggestions emojis

### ISSUE THREAD

**Issue by sttephen** [learnspigot/discord-bot#125]
Please change the emojis to these:
![image](https://user-images.githubusercontent.com/35041891/216665251-7a371f78-3504-4a09-9d91-f84786fe6914.png)

As opposed to this, as it is very inconsistent...
![image](https://user-images.githubusercontent.com/35041891/216665361-22e5c570-17f2-4718-89c9-3178a22ab26c.png)

Upvote: 896862259425447986
Downvote: 896862278186598502

**Comment by Zcamt** [comment]
This has to be changed in the .env file by anyone who has access to the files used in production
![image](https://user-images.githubusercontent.com/37076791/216721184-fa7f7bae-6483-45d7-91bb-8b2b0b4159ea.png)

**Comment by joshdevous** [comment]
This has been implemented in 3.0
