### ISSUE TITLE
Adding "value" as a field to a rep

### ISSUE THREAD

**Issue by Zcamt** [learnspigot/discord-bot#129]
This might be difficult to switch to, but I'd love it if we had a way to add value to a rep, making one "point"/entry count for more, as currently, it feels janky that receiving multiple rep from a tutorial fx will end up being 2-10 "individual" points and just floods /rep, instead I think it'd look nice if it were condensed into smth like "5 rep from #some-channel"

**Comment by joshdevous** [comment]
This has been implemented in 3.0
