### ISSUE TITLE
[Enhancement]: Star board

### ISSUE THREAD

**Issue by Nuckerr** [learnspigot/discord-bot#141]
### Explain your idea.

When a message receives x amount of reactions of the star emoji (say 10), the message gets sent (in an embed) to a #starboard channel.
This channel would be public (to students), and any student could react with stars for the starboard.

An example from another server:
![image](https://github.com/flytegg/ls-discord-bot/assets/62883418/68f897cd-7d6a-4392-8f0e-6fab9d703a93)
![image](https://github.com/flytegg/ls-discord-bot/assets/62883418/0a18ba7a-fac6-4e5a-a47f-c0101985dd71)

**Comment by sttephen** [comment]
+1 love the idea

**Comment by Nuckerr** [comment]
In regards to implementation:
- Listen to every reaction in the sever with a star
- When it reaches x amount, forward it in an embed to a channel
- Store that id in a database
- Listen to when it gets more reactions to update the forwarded message?

**Comment by awkkih** [comment]
Good idea, just remove #support from that...

**Comment by Nuckerr** [comment]
what?

**Comment by sttephen** [comment]
I think he's saying don't make messages in #support eligible for starboard

**Comment by Nuckerr** [comment]
oh, not sure about this because sometimes messages from #support should appear on a starboard, especially since its one of the most active channels.
If there is a risk of something secret getting into the starboard, perhaps there could be an context app to block a message from the starboard.

**Comment by sttephen** [comment]
> oh, not sure about this because sometimes messages from #support should appear on a starboard, especially since its one of the most active channels. If there is a risk of something secret getting into the starboard, perhaps there could be an context app to block a message from the starboard.

I love that idea. Perhaps the context app adds some sort of red reaction like :no_starboard: or something so that people also don't vote stars.

**Comment by stephendotgg** [comment]
@revelcw 
3 issues with your impl
- Images dont work (suggested by snat)
- Removing a star removes the whole msg even if > required stars
- no starboard emoji does not work

**Comment by revelcw** [comment]
> @revelcw 3 issues with your impl
> 
> * Images dont work (suggested by snat)
> * Removing a star removes the whole msg even if > required stars
> * no starboard emoji does not work

Originally images had a good reason not to work but I can get to them with the fix.
The other two worked for me and I have no idea why it doesn't work but I'll do some debugging
