### ISSUE TITLE
Reopen closing knowledgebase posts/projects

### ISSUE THREAD

**Issue by sttephen** [learnspigot/discord-bot#142]
Posts seem to automatically close after X time and I think we can adjust this but not disable it within the ui. The bot should just reopen any post which closes. Closed posts are a problem because they cannot be referenced with #, so especially for suggesting knowledgebase items.

**Comment by sttephen** [comment]
This would be a great one to tackle as it allows us to reference our knowledgebase/projects all across the server.

Some context:

"After a certain period of inactivity - 7 days by default - a Threads will automatically close, clearing away the clutter in your channel sidebar for everyone visiting the channel."

However, this is not the same as the "HIDE AFTER INACTIVITY" setting in the forum help channel. That simply hides the posts from the sidebar. In my opinion, these are two different settings.

What isn't up for debate, is that there is nothing we can do within the client UI to stop these posts from closig after X time. I'm thinking there is probably a thread / forum post close event which we can use to just reopen them. (Hopefully)

**Comment by Pan-nav** [comment]
I can probably have a go at this

**Comment by sttephen** [comment]
> I can probably have a go at this

🐐

**Comment by revelcw** [comment]
@sttephen can this be closed

**Comment by joshdevous** [comment]
Closed by #150
