### ISSUE TITLE
[Bug]: Interaction fails when responding to a profile verification if user has DMs disabled

### ISSUE THREAD

**Issue by joshdevous** [learnspigot/discord-bot#144]
### Explain the issue.

When approving/denying a profile verification, the interaction will time out if the user has DMs disabled due to not handling the error.

![image](https://github.com/flytegg/ls-discord-bot/assets/43449531/563a17d0-ccb9-40aa-b8aa-30ea31e23048)

### How to recreate?

Try to press one of the interaction buttons under a profile verification.

**Comment by sttephen** [comment]
This is odd. We do seem to handle this error in the code
https://github.com/flytegg/ls-discord-bot/blob/master/src/main/kotlin/com/learnspigot/bot/profile/ProfileListener.kt

Are we misunderstanding how to handle it?

**Comment by sttephen** [comment]
We should look into the ErrorHandler#ignore method rather than handle since we don't actually need a block of code to run, but I'm not convinced it should throw that behavior. I don't think it did on the Java one

**Comment by joshdevous** [comment]
> This is odd. We do seem to handle this error in the code
> 
> https://github.com/flytegg/ls-discord-bot/blob/master/src/main/kotlin/com/learnspigot/bot/profile/ProfileListener.kt
> 
> 
> 
> Are we misunderstanding how to handle it?
> 
> 

Potentially we're doing it wrong... it might be worth mentioning I only tested this clicking the "wrong link" due to that being the case for that verification - I haven't looked at the code to double check if it could differ per response type (but I assume not)

**Comment by sttephen** [comment]
Oh @joshbker. Wtf. We got confused. The error in console points to ProfileListener. Go look in that class and see what it does. That's the bloody join message! Looks like failed verification was a different error with no console output. That makes this easier because I know he left the server so we have some sort of issue there we can narrow down

**Comment by joshdevous** [comment]
Oh I'm blind, just assumed. Let's go over this later and sort it out

**Comment by awkkih** [comment]
@joshbker I couldn't recreate the issue, even with my DMs disabled. I just get no message from the bot and no errors too. Maybe a random error which popped up?
Also, this already looks fixed as when the message is queued, it handles the closed DM with `ErrorHandler().handle(ErrorResponse.CANNOT_SEND_TO_USER) {}`

**Comment by stephendotgg** [comment]
IIRC I fixed it by adding that line of code
