### ISSUE TITLE
[Enhancement]: Less manual JetBrains key giving

### ISSUE THREAD

**Issue by joshdevous** [learnspigot/discord-bot#152]
### Explain your idea.

Use Google Docs API to hook into a Google Sheets containing JetBrains license keys so the bot has access to keys.

From here have an Admin only command, `/givekey <@user>`, which takes an unused key from the sheet and sends them a DM with it if they Student role, otherwise say that they haven't verified ownership of the course.

### Anything else?

Could also introduce a `/requestkey` command off the back of this, however that would require tracking who already has been given one.

**Comment by Zcamt** [comment]
Can't promise I'll make it work, but sounds like an interesting system, will take a crack at it

**Comment by stephendotgg** [comment]
Donezo

**Comment by stephendotgg** [comment]
Added /getkey (student) and /keysleft (manager) commands
