### ISSUE TITLE
[Bug]: Rep management command not functioning.

### ISSUE THREAD

**Issue by Pan-nav** [learnspigot/discord-bot#159]
### Explain the issue.

Both the addrep and removerep commands have not been functional for quite some time. The application does not respond for either.

![image](https://github.com/flytegg/ls-discord-bot/assets/102317251/6f82ad1d-e8e4-446a-be6c-71be7fc5882c)
![image](https://github.com/flytegg/ls-discord-bot/assets/102317251/fa719440-0f5c-4c5b-901e-353f7dca359a)

### How to recreate?

Easy to recreate, just use the command on anyone. (I used it on myself for testing purposes).

**Comment by sttephen** [comment]
Analysis: Is brokey

**Comment by joshdevous** [comment]
Fixed by 485e9b98896731bc86e1a0ef86dab54261dbc351
