### ISSUE TITLE
[Enhancement]: Add an "undo" button on profile verification for special staff members

### ISSUE THREAD

**Issue by joshdevous** [learnspigot/discord-bot#160]
### Explain your idea.

![image](https://github.com/flytegg/ls-discord-bot/assets/43449531/49eac8f8-fb1c-46b3-8b03-2f3178fe6169)

Clicking this would undo the verification process, as well as DMing the user saying sorry for the mistake... opening up the original message to have the buttons pressed again

**Comment by stephendotgg** [comment]
Done by goat @Zcamt
