### ISSUE TITLE
Make #suggestions message like #showcase

### ISSUE THREAD

**Issue by stephendotgg** [learnspigot/discord-bot#174]
The embed is huge fluffery and unnecessary.

Make the format exactly like showcase where it just adds a thread and reactions to user, this means no fluff AND more importantly the user can delete their own message so when people accidently type in there they can get rid of it.

Also change thread name to "Suggestion from <name>" like "Showcase from <name>".

**Comment by awkkih** [comment]
Can do, will try to make it today
