### ISSUE TITLE
Command to search knowledgebase 

### ISSUE THREAD

**Issue by stephendotgg** [learnspigot/discord-bot#184]
@MLGPenguin's idea

like /knowledgebase how to make start.bat

Online start.bat Generator
Common issue with start.bat
unsupported java version start.bat

Just copy the embed from /lecture, keep format the same
(USE PENGUIN'S SEARCH ALGORITHM ALREADY BUNDLED)

**Comment by MLGPenguin** [comment]
It would also be super epic if EITHER the embed had a button underneath "was this useful?" which awarded a rep to the creator of the post when the OP selects "yes" (add safeguard in case multiple people run the command) OR the title of the knowledge base post were to be added to the contributors menu when selecting contributors for rep, resulting in the same outcome (rep to the knowledgebase post creator)

BONUS POINTS
Add a section to the database which keeps track of how many times each post has been deemed "useful"

*Make this a separate issue if you choose not to do it, thanks :)*

**Comment by stephendotgg** [comment]
Great great idea. I vote #2 just for minimum bulkyness. Would be sick

**Comment by stephendotgg** [comment]
i will make

**Comment by stephendotgg** [comment]
Done. And done Penguins option # 2.
