### ISSUE TITLE
/lecture command gone

### ISSUE THREAD

**Issue by Pan-nav** [learnspigot/discord-bot#192]
### Explain the issue.

idfk everytime one command gets added the other gets removed 🗿

**Comment by awkkih** [comment]
can confirm it's not Discord limiting commands as we tested out with Snuggles /test command

**Comment by Pan-nav** [comment]
> can confirm it's not Discord limiting commands as we tested out with Snuggles /test command

![image](https://github.com/flytegg/ls-discord-bot/assets/102317251/59eda650-d8b0-49a6-8350-68804deb5f9d)
I agree.

**Comment by Dawsson** [comment]
Have we figured out the issue? Is it related the Neptune?

**Comment by joshdevous** [comment]
@stephendotgg is this closed by a607559f8783f184b5b3895d7b242c89ce8ba1e3 ?

**Comment by joshdevous** [comment]
After some recent updates to Neptune and the bot's registering of integrations/commands this looks to be resolved. Can re-open if this bug is introduced.
