### ISSUE TITLE
Send message in thread similar to what modrinth does

### ISSUE THREAD

**Issue by Dawsson** [learnspigot/discord-bot#193]
### Explain your idea.

Have a message explain a few things, the ai assistant, and /close when thread is finished?
Example from modrinth:
Please allow some time for a response! In the meantime, please take a look at our [Frequently Asked Questions](https://docs.modrinth.com/docs/faq) to see if your question is already answered.

Please use `/thread archive` once your thread is resolved!

**Comment by awkkih** [comment]
I can do this

**Comment by stephendotgg** [comment]
I agree completely. Rn people don't know /close exists. Also maybe a link to guidelines post as well? So they can rectify any wrongdoing

Also - whoever makes this, please make it so the message will delete on close. I really hate looking through old posts and they're just full of our system messages, this is one we can definitely get rid of on close. (Just delete first thread message after user)

**Comment by stephendotgg** [comment]
Oh shoot I did not see the PR, @akkih any chance you could add it?

**Comment by stephendotgg** [comment]
Oops I just tagged some asian guy

**Comment by awkkih** [comment]
LOL, of course, gib me a few minutes baby

**Comment by Dawsson** [comment]
Was this completed? I can work on this as I need a similar feature in the bot framework

**Comment by stephendotgg** [comment]
i think akkih prd it but he only did the first part I think, would be really preferable imo if the message could delete to reduce clutter

**Comment by awkkih** [comment]
this is the issue, i can't seem to get the message when the thread is closed

**Comment by stephendotgg** [comment]
@akkkih you could delete the message before you close the thread?

**Comment by awkkih** [comment]
yes i could however this is the problem lmao, somehow it's not able to retrieve the message so it just doesn't work
i'll try to continue working on this asap, just need to finish some personal stuff atm :D

**Comment by joshdevous** [comment]
> yes i could however this is the problem lmao, somehow it's not able to retrieve the message so it just doesn't work i'll try to continue working on this asap, just need to finish some personal stuff atm :D

I'd recommend using complete to fetch and delete the message rather than queue, then queue the closing of the thread after. Should hopefully hold the thread open while it's deleting a message

**Comment by awkkih** [comment]
will try this!
