### ISSUE TITLE
/rep behind on counter

### ISSUE THREAD

**Issue by Dawsson** [learnspigot/discord-bot#196]
### Explain the issue.

![image](https://github.com/flytegg/ls-discord-bot/assets/88049488/c5592b97-3151-4dfd-bf5b-c133c7d068bf)
The number on the right needs to be one higher. Lists start at 0 :(

### How to recreate?

/rep user

**Comment by joshdevous** [comment]
As unintuitive as this probably is, it's correct. It's an ID for the user's rep, so one might be deleted but that doesn't mean the number will shift. This way specific reps or a range of rep can be removed using the ID.

Maybe we could improve this system though?

**Comment by stephendotgg** [comment]
I agree with Josh, mainly for the fact that these IDs are the ones which are in the database and can be removed using the remove command, will only cause confusion to +1

good issue though, these are the sorts of things that I appreciate :)
