### ISSUE TITLE
Add auto deploy to ptero

### ISSUE THREAD

**Issue by stephendotgg** [learnspigot/discord-bot#199]
Using https://github.com/flytegg/ptero-build-flow

Note: If bot is going to be restarting more often we should probably add some code to clear the verify and leaderboard channels before sending the new ones. We dont necessarily need to clear verify, moreso just stop the new one sending, but we definitely do need to clear leaderboard as I don't want to be deleting these constantly

**Comment by joshdevous** [comment]
> Using https://github.com/flytegg/ptero-build-flow
> 
> Note: If bot is going to be restarting more often we should probably add some code to clear the verify and leaderboard channels before sending the new ones. We dont necessarily need to clear verify, moreso just stop the new one sending, but we definitely do need to clear leaderboard as I don't want to be deleting these constantly

Easy enough to delete these I think, we can just get channel message history and clear them all.

**Comment by joshdevous** [comment]
Happy to set this up tomorrow

**Comment by Dawsson** [comment]
I can do this also if needed, I have to do this for 3 or so other bots so may as well while I'm at it. Just lmk today

**Comment by stephendotgg** [comment]
> I can do this also if needed, I have to do this for 3 or so other bots so may as well while I'm at it. Just lmk today

that would be cool thank you robot man
