### ISSUE TITLE
Officially integrate business udemy profiles into verification

### ISSUE THREAD

**Issue by Nuckerr** [learnspigot/discord-bot#2]
Users get given access to lots of udemy courses through their employment including learnspigot. Someway to enhance this.

**Comment by sttephen** [comment]
This is going to be a challenge. Business accounts have no front facing profile. Any ideas?

I can think of many, but none which reduce the human aspect to as little as a verify command.

**Comment by Nuckerr** [comment]
What do you look for when verifying its a business account? Or is there literally nothing and its just over trust?

**Comment by sttephen** [comment]
Going to be honest... mostly trust. However, if someone tells me their name I am able to verify on my panel that they are a Student. But I can't think of how to automate this without risking my account.

**Comment by joshdevous** [comment]
No longer required with 2.0 due to new verification flow
