### ISSUE TITLE
Star Count Off

### ISSUE THREAD

**Issue by Dawsson** [learnspigot/discord-bot#200]
### Explain the issue.

star count is 9 on starboard, 6 on physical message

### How to recreate?

![image](https://github.com/flytegg/ls-discord-bot/assets/88049488/6d7ef30b-b325-46e7-aa3a-26343fa28b58)
![image](https://github.com/flytegg/ls-discord-bot/assets/88049488/25854a6f-7d01-4518-a0f1-3c1ccbf60b09)

**Comment by revelcw** [comment]
Looks completely fine to me now, think you're just having discord caching issues!

**Comment by Difluoride** [comment]
Updated on my side too. A similar issue was identified back in July in main LS Discord, unsure if related to a potential Discord caching issue

![IMG_4545](https://github.com/flytegg/ls-discord-bot/assets/6743795/d3025c38-b6e2-43ea-ac19-eedc7e7b1f6f)

**Comment by Nuckerr** [comment]
Almost certainly

**Comment by awkkih** [comment]
> Updated on my side too. A similar issue was identified back in July in main LS Discord, unsure if related to a potential Discord caching issue
> 
> ![IMG_4545](https://github.com/flytegg/ls-discord-bot/assets/6743795/d3025c38-b6e2-43ea-ac19-eedc7e7b1f6f)
> 

I think the starboard revamp came after July, so that's a problem that's probably been fixed

**Comment by awkkih** [comment]
It works fine on my end, probably just a cache error or the bot went offline.
You can test this with any message that's on the starboard already. Probably the bot went off for a few minutes and that was enough for it not to update the embed.

**Comment by stephendotgg** [comment]
Just Discord being Discord.
