### ISSUE TITLE
DM message showing wrong reputation 

### ISSUE THREAD

**Issue by night0721** [learnspigot/discord-bot#226]
### Explain the issue.

When a staff receive a reputation, they should receive a dm message from bot saying you gained a reputation, but embed content is saying “You gained one reputation” still even though you have 2 reps gained

### How to recreate?

Give some staff 2 or more reps with dm on

### Anything else?

Tell me if I should pr or not

**Comment by joshdevous** [comment]
Closed by f6aa78a1aae1b17c6ce027128beb64906b12d9f6
