### ISSUE TITLE
Knowladgebase message selectable on /close

### ISSUE THREAD

**Issue by LitleProgrammer** [learnspigot/discord-bot#227]
### Explain the issue.

If you run /close in a help thread and somewhere in the conversation a user ran the /knowledgebase command it can be selected as a contributor. I'm not 100% sure if this is a bug or a feature but I think I'm going to report it never the less.
![Bildschirmfoto 2024-01-27 um 20 14 09](https://github.com/flytegg/ls-discord-bot/assets/87831625/40bed731-063f-484b-8503-39702fa1eb8f)
![Bildschirmfoto 2024-01-27 um 20 14 00](https://github.com/flytegg/ls-discord-bot/assets/87831625/c376729b-6558-48d3-9c0f-c2372abf71cf)

### How to recreate?

Open a help thread run /knowledgebase in the conversation and close the thread.
https://discord.com/channels/397526357191557121/1200525537731416116

**Comment by Dawsson** [comment]
Thats intentional, its so we can give credit to those who created knowledgebase threads.

Thank you for the post! Have a good day
