### ISSUE TITLE
Interaction fails for staff selecting reputation on users behalf

### ISSUE THREAD

**Issue by sttephen** [learnspigot/discord-bot#23]
### Explain the issue.

In the case of a thread where the OP has done a runner, management may need to run /close and select contributors on their behalf.

Currently, we can close it but interaction fails at selecting contributors.

I discussed this with @Nuckerr that this was to be the intended impl. Currently the only solution is to manually add rep which is not the best.

**Comment by Nuckerr** [comment]
Staff and above for permissions or management?

**Comment by sttephen** [comment]
> Staff and above for permissions or management?

Management
