### ISSUE TITLE
Sending a large number in #counting stalls the bot

### ISSUE THREAD

**Issue by Tofpu** [learnspigot/discord-bot#250]
### Explain the issue.

Sending a large number ([example](https://paste.learnspigot.com/anafavumik)) in `#counting` channel freezes the bot, causing every functionality to not work anymore (i.e: `/rep`). I assume it has to do with the math evaluate method taking a while processing the number, which causes everything else to stall, as every other functionality gets processed on the same thread.

### How to recreate?

Send a very large number ([example](https://paste.learnspigot.com/anafavumik)), and it'll stall out the bot.

### Anything else?

I think the ideal solution here would be to:
1. Run math calculations in its own dedicated thread
   - That way, this wouldn't disrupt other functionalities of the bot (i.e: help channels, verification; assuming they're all ran in the same thread)
2. Abort the calculation after some specified time (i.e: 5 seconds).
   - That way, somebody could not grief by sending a large number, like I did.

**Comment by MLGPenguin** [comment]
Not sure exactly why this happens as generally the math evaluator will do Integer.parseInt and call it a day if that fails. But there is currently a PR (#249) waiting for submission which is a complete re-write of the eval which would (hopefully) fix this. Will run some preliminary tests to make sure, thanks for pointing this out.

**Comment by MLGPenguin** [comment]
Fixed in #249
