### ISSUE TITLE
[Enhancement]: make /verifyother nicer

### ISSUE THREAD

**Issue by SimplyMerlin** [learnspigot/discord-bot#29]
### Explain your idea.

as of now, /verifyother works fine, but it could be enhanced.

- The message currently says you have been verified, this is obviously incorrect. I would suggest changing this to "[name] has successfully been verified.".
- /verifyother could potentially remove every message from the targeted user in the verified channel. The lazy way to do this is delete all their messages in the channel this command is ran in, but this is asking for problems. Adding a env variable for the verified channel and then deleting all messages there from the targeted user would be the way to do this i suppose.

**Comment by Nuckerr** [comment]
Removing there messages is functionally which could be added to the entire verification system. Good shout.

I am aware that the message welcomes the sender, however the code isn't set out well to improve that. Really I just couldn't be arsed. It's not as if many people see it. However someone could give this a bash
