### ISSUE TITLE
[Bug]: Lecture searching needs improving

### ISSUE THREAD

**Issue by Yando0** [learnspigot/discord-bot#31]
### Explain the issue.

whenever i type lecture name specficlly and correctly it gives me another lecture that isnt even close to the search  

### How to recreate?

search anything

**Comment by sttephen** [comment]
Hi YAndooyellow. Thanks so much for reporting. We will look into this. Could you use your technical expertise to advise us on the best path forward?

**Comment by SimplyMerlin** [comment]
I searched something and it works for me?
![image](https://user-images.githubusercontent.com/30577208/207929784-dbde72ce-cf80-4d29-b407-97cc83cb495f.png)

**Comment by sttephen** [comment]
Congratulations! You have won the a random prize for creating an issue. We are giving these away every 20 issues made. Please seend your PayPal and we'll shoot over the $50 prize.

**Comment by Nuckerr** [comment]
See #25 - not sure if this is deployed yet. Also in future, please be more mature with your naming and description of the issue. 'Dumb' does not help us

**Comment by Nuckerr** [comment]
Will be solved with #61
