### ISSUE TITLE
Poll command

### ISSUE THREAD

**Issue by SimplyMerlin** [learnspigot/discord-bot#53]
### Explain your idea.

you can do a /poll which will create a fancy embed with 2-4 buttons which let you select an option. i want to do polls all the time just like elon musk chief twit elon. the amount of times i want to know something is huge. please, add this.

**Comment by night0721** [comment]
@SimplyMerlin number of buttons according to number of options given in command?

**Comment by SimplyMerlin** [comment]
Yes! Apart from that the message that has the buttons should just contain the options for the poll, the percentage of people voting on each option, and how many people voted in total.

**Comment by night0721** [comment]
Ok I'll do it

**Comment by Nuckerr** [comment]
I'm working on this. Check assignments
