### ISSUE TITLE
Visual improvements to closing a ticket

### ISSUE THREAD

**Issue by sttephen** [learnspigot/discord-bot#54]
### Explain your idea.

See current setup: https://i.imgur.com/07HbRb8.png

- I think it would be best if the entire selecting process could be deleted once it has been used. That is, all that is left is "X has closed the thread". There is no need for the selector and Close button to remain there while disabled and just looks clunky!

- I think it should say who has been given rep. The three formats:
  - "Aroze closed the thread, listing @stephen as a contributor."
  - "Aroze closed the thread, listing @stephen and @nucker as contributors."
  - "Aroze closed the thread, listing @stephen, @nucker, X, Y, Z and @Lukas as contributors."

Any better format idea is welcome.

**Comment by Nuckerr** [comment]
Sounds good. What if no contributors are awarded

**Comment by sttephen** [comment]
Sorry, pardon my stupidity!

I would suggest just:
"Aroze closed the thread, listing no contributors."

**Comment by Nuckerr** [comment]
Np, thanks!
