### ISSUE TITLE
Add /embed command

### ISSUE THREAD

**Issue by sttephen** [learnspigot/discord-bot#65]
### Explain the issue.

An embed command which produces an embed

Required args:
- Channel to send it in
- Title
- Description

Optional args:
- Footer
- Thumbnail
- Image
- Author
- Color (IF NOT COLOR PROVIDED, PLEASE USE THE DEFAULT ONE WE USE FOR EVERY OTHER EMBED)

Make this command on the same perms level as /forceverify

**Comment by revelcw** [comment]
I am fine with doing this. How soon would you want this out?

**Comment by sttephen** [comment]
> I am fine with doing this. How soon would you want this out?

No rush, more of a nice-to-have.

**Comment by Zcamt** [comment]
> I am fine with doing this. How soon would you want this out?

Assigned you to this then @revelcw

**Comment by awkkih** [comment]
Solved.
