### ISSUE TITLE
[Enhancement]: Let env variables be empty

### ISSUE THREAD

**Issue by SimplyMerlin** [learnspigot/discord-bot#69]
### Explain your idea.

the learnspigot bot is quick to shoot itself in its foot when any env variable is null, ever. Certain parts of the bot could gracefully be disabled instead of shutting the bot off completely!

**Comment by Nuckerr** [comment]
The bot will only fail if it needs the .env. Also I think this is a bit over the top as in the end it will used with all features. We would just end up with lots of code checking if a .env is not null

**Comment by SimplyMerlin** [comment]
This is ridiculous. The bot won't run without a forum linked and I don't own a single server where I can create a forum.

**Comment by Nuckerr** [comment]
You need to make the server a community server. If you want you can pr this, and if the code isn't too bad then I'll merge.

**Comment by revelcw** [comment]
I agree with Nuckerr. Filling all the requirements of the .env isn't that hard and checking that certain vars are left blank is unneccecery.

**Comment by Zcamt** [comment]
> This is ridiculous. The bot won't run without a forum linked and I don't own a single server where I can create a forum.

Servers should come with forums now, I created an entirely new server for testing the bot and I got forums on it within a couple of minutes after making it a community server.
