### ISSUE TITLE
Need a way to support personal subscriptions for verification (and perhaps periodically remove)

### ISSUE THREAD

**Issue by sttephen** [learnspigot/discord-bot#72]
### Explain the issue.

I come armed with few answers, but wanted to start a discussion on this to share our collective knowledge so we can achieve this.

Our friends at Udemy introduced personal subscriptions. I have no idea if they have profiles or not, but I know none of them can verify. I have not had one recenty so nobody to question about it.

Whatever the story, our bot doesn't like them. @Nuckerr hoping you can provide some insight.

**Comment by Nuckerr** [comment]
What are personal subscriptions?

**Comment by sttephen** [comment]
@Nuckerr Sorry to link you, but read this:
https://support.udemy.com/hc/en-us/sections/1500000478402-Subscriptions

It's a Skillshare type system. Everyone on them complains to me they can't verify

**Comment by Nuckerr** [comment]
When you next get a personal subscription profile, dm me

**Comment by joshdevous** [comment]
No longer required with 2.0 due to new verification flow
