### ISSUE TITLE
'/managerep add' does not respond to user

### ISSUE THREAD

**Issue by sttephen** [learnspigot/discord-bot#73]
### Explain the issue.

Adds rep, no interaction response. Causes some confusing situations!

**Comment by Zcamt** [comment]
I've tested on the live bot, on the LS discord and there does indeed seem to be an issue, however, I've pulled the most recent version of the repo and tried running it locally and I can't reproduce it, both add and remove work just fine.

Could this be an issue with mongo? Cause it doesn't seem to be the code itself

**Comment by sttephen** [comment]
@Nuckerr - can you provide any info that could help?

**Comment by SimplyMerlin** [comment]
> @Nuckerr - can you provide any info that could help?

same problem on /profile, seems to be a generic issue on prod instead of current build

**Comment by Nuckerr** [comment]
Unable to reproduce
![image](https://user-images.githubusercontent.com/62883418/209428046-f507490c-1a1b-448e-bfc5-a386dbdac8d4.png)

**Comment by Nuckerr** [comment]
I'll update prod today so any issues will be ironed out
