### ISSUE TITLE
Remind user that we have paste.learnspigot.com when Hastebin links are sent

### ISSUE THREAD

**Issue by sttephen** [learnspigot/discord-bot#75]
### Explain the issue.

As per title. Especially useful for the help section. We want it used as much as possible!

**Comment by Nuckerr** [comment]
I'm gonna one you up: if we detect an alternative pastebin (eg hastebin.com/pastebin.com), we convert to it to `paste.learnspigot.com` and remind the user. The reason we have paste.learnspigot.com is because hastebins expires, paste.learnspigot.com should not expire. We need that for archival

**Comment by sttephen** [comment]
> I'm gonna one you up: if we detect an alternative pastebin (eg hastebin.com/pastebin.com), we convert to it to `paste.learnspigot.com` and remind the user. The reason we have paste.learnspigot.com is because hastebins expires, paste.learnspigot.com should not expire. We need that for archival

Great idea Nucker! +1

**Comment by revelcw** [comment]
@Nuckerr wait are you still working on this? i was going to take a crack at it.

**Comment by awkkih** [comment]
You can also remember them when a big chunk of code is sent!
Not sure how to detect that, but I'm pretty sure it is possible 😄

**Comment by revelcw** [comment]
> You can also remember them when a big chunk of code is sent! Not sure how to detect that, but I'm pretty sure it is possible 😄

That was also an idea; if not, I could see implementing more of these abilities inside the message context menus.

**Comment by stephendotgg** [comment]
![image](https://github.com/flytegg/ls-discord-bot/assets/138625055/1f53057c-d6f4-425a-ad99-b145da334ff2)
Done. (Emoji will work on prod)

Supports these pastebins.
        "pastebin.com",
        "paste.md-5.net",
        "paste.helpch.at"

To add more just add to the list as long as they are a haste server. Someone can look @ adding hastebin in the future though it's trash now and doesn't work like all the haste-servers do, not sure it's well used anymore.

Thanks Nucker for the great idea!
