### ISSUE TITLE
Create a vote for Managers on tutorial/project creation

### ISSUE THREAD

**Issue by sttephen** [learnspigot/discord-bot#76]
### Explain the issue.

For those who aren't aware: posting in tutorials or projects can now earn your reputation.

The plan is to hold a vote and give between 0-5 rep inclusive depending on lots of factors but mainly quality.

Sadly there isn't really a metric, these have to be human reviewed.

- Make it so that when a tutorial/project is made, it pings Manager (790695546704494643) in the Manager chat (749008427799281704) and the following embed:
![image](https://user-images.githubusercontent.com/35041891/209424440-e430eb0f-db20-4596-9fe8-39e3da10c055.png)
- It should auto add reactions: 0,1,2,3,4,5
- End the vote after 12 hours, giving a rounded average of the most popular rep choice.
- If post/tutorial has been deleted when it comes to giving the rep, don't give the rep
- Could send a cool message in Support (398279082996924416) saying X got Y rep from Z tutorial/project

**Comment by Nuckerr** [comment]
Is it worth putting this in the bot?

**Comment by sttephen** [comment]
@Nuckerr My argument would be yes. This is because every time a tutorial is created I'm going to have to ping, add the reactionss, check to make sure everyone has voted, remove my reactions, wait till 12 hours is up, check if the post is still there or not, calculate the average, assign the rep, message them in support to say we decided to give X rep and then somehow remember not to vote again on that particular tutorial.

This is very much a nice-to-have, but I don't think it could be argued that this feature has no place.

**Comment by Nuckerr** [comment]
I see. I assumed this would be a lot more informal, having it just be discussed in manager chat before being awarded rep manually

**Comment by joshdevous** [comment]
As mentioned in #114 before closing, it would be good for this rep reward to be announced in support, in the exact same way rep rewarded for help posts is.

Maybe something like:
"@stephen has received a reputation from contributing in #help-post"
"@stephen has received 7 reputation for #my-cool-project"

**Comment by sttephen** [comment]
Making new issue with different details.
