### ISSUE TITLE
Reopen thread on user thread close

### ISSUE THREAD

**Issue by sttephen** [learnspigot/discord-bot#80]
### Explain the issue.

When a user goes to close a thread manually, reopen the thread and run /close on their behalf.

**Comment by Zcamt** [comment]
Can't seem to find a good way to fix this issue.
The only event I can find is this: https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/events/channel/update/ChannelUpdateArchivedEvent.html

And that doesn't help us much as it won't allow us to check *who* actually closed the thread, just that it got closed, meaning this'll then trigger when the bot closes the ticket when /close is used.

**Comment by sttephen** [comment]
If that is the only event, we can do this no problem. It reminds me of some stupid shit in Spigot where you can't tell who did what. The solution would just be to store some info in memory when we're closing it so that when this event fires it knows not to reopen it, otherwise reopen it as it was a user.

The only remaining problem is that as a Manager/me, I am not going to be able to bypass this. Perhaps a /forceclose command or something.

**Comment by Zcamt** [comment]
Why would we need a forceclose, can't we just use /close if we want to close a thread? 

I might just be missing something haha

**Comment by sttephen** [comment]
Yeah, I was more thinking for broken threads, like an emergency stop button! Or ones that have been closed and got reopened type thing. Not the end of the world if we cannot do this though, just a nice to have. =)

**Comment by Zcamt** [comment]
Ahh okay, will look into that too then :D

I think I have an idea for the event stuff, that doesn't require having to save something in memory, tho it'll still be kinda hacky. 
We get access to the channel instance, so I could check if the most recent message was sent by the bot, if that's the case we know /close was used right?

The only way this doesn't work is if someone uses /close and then manually closes it after that, but I think that could be the case with the memory solution.

**Comment by sttephen** [comment]
Sadly one of those cases where I think the only solution is hacky. But definitely possible and can be airtight.

That is definitely a solution, though I fear because the bot can be slow and people like to talk a lot this could fuck up occassionally.

My suggestion is this:

- On bot close, store post ID in memory, "dontReopen" list
- On event, check if in "dontReopen" list, if so remove from list and do nothing
- If not in list, reopen!

**Comment by Zcamt** [comment]
> My suggestion is this:
> 
> * On bot close, store post ID in memory, "dontReopen" list
> * On event, check if in "dontReopen" list, if so remove from list and do nothing
> * If not in list, reopen!

And I assume we'd have to do this when /close is used then.
Cause if we assume the bot is/could be slow, can we expect it to be fast enough to store into memory when the close button is clicked and then just moments after the event would fire?

**Comment by sttephen** [comment]
Nono I would do this when someone clicks the big red Close button
It doesn't really matter how slow the bot is, as long as the code sequence is fine. We put in memory before we actually close the post, meaning the event simply has to fire after!

**Comment by Zcamt** [comment]
> Nono I would do this when someone clicks the big red Close button It doesn't really matter how slow the bot is, as long as the code sequence is fine. We put in memory before we actually close the post, meaning the event simply has to fire after!

I guess I overthought this, will do this then
