### ISSUE TITLE
[Enhancement]: Bot bumps post after inactivity

### ISSUE THREAD

**Issue by MLGPenguin** [learnspigot/discord-bot#82]
### Explain your idea.

There's been some recent clashes between staff members bumping posts and receiving rep for doing so, this has been capitalised on by the more _enthusiastic_ support members so I would like to propose somewhat of a solution.

As the title describes, after a set amount of time (perhaps every 8 or 12 hours), the bot will ping the OP asking them if the issue has been resolved or not and providing prompts on what to do if it has / has not, this will remove the need for staff members to bump posts and make the threads look a little more professional (since automation is always a sign of professionalism!)

### Anything else?

Underneath the prompt could be two buttons, a close button (which would imitate the user running /close and displaying those prompts) and a .. not-close button, which could ping all of the staff members who were involved in the post thus-far.

**Comment by Nuckerr** [comment]
Sounds good

**Comment by sttephen** [comment]
Happy with /ping solution for now. Think the issues have calmed down.
