### ISSUE TITLE
Filter those who haven't sent messages in threads for contributors

### ISSUE THREAD

**Issue by Nuckerr** [learnspigot/discord-bot#84]
### Explain the issue.

https://github.com/learnspigot/discord-bot/blob/70c36fc2d6a3e95c592493d5b15fb6bd7ca45568/src/main/kotlin/com/learnspigot/bot/manager/ForumManager.kt#L86-L92

To get contributors, it gets all thread members and does not filter those who have not sent any messages. This could be simple filter function. See 
https://github.com/learnspigot/discord-bot/blob/70c36fc2d6a3e95c592493d5b15fb6bd7ca45568/src/main/kotlin/com/learnspigot/bot/manager/ForumManager.kt#L89-L91
To see how to get message count.

**Comment by Tofpu** [comment]
If I'm not mistaken, this has been addressed recently: https://github.com/flytegg/ls-discord-bot/pull/241

**Comment by MLGPenguin** [comment]
This is completed
