### ISSUE TITLE
[Bug]: addlookup command broken

### ISSUE THREAD

**Issue by Zcamt** [learnspigot/discord-bot#86]
### Explain the issue.

Using /addlookup results in an error atm.

### How to recreate?

use /addlookup

**Comment by Nuckerr** [comment]
Is this tested locally? Can you get a stacktrace?

**Comment by Zcamt** [comment]
> Is this tested locally? Can you get a stacktrace?

Not tested locally yet, only tested on live build on the discord, will test locally now.

**Comment by Zcamt** [comment]
@Nuckerr, I pulled the most recent build and tested it, works as it should - could this be connected to #73?

**Comment by Nuckerr** [comment]
The bot probably needs a restart

**Comment by Zcamt** [comment]
Issue continues in #94
