### ISSUE TITLE
Discord timestamp in rep leaderboard footer

### ISSUE THREAD

**Issue by sttephen** [learnspigot/discord-bot#9]
### Explain your idea.

Would be cool to use the localized timestamp instead of current message

**Comment by Nuckerr** [comment]
We cannot have timestamps in the footer, the only way would be to move the timestamp somewhere else that supports timestamps

**Comment by sttephen** [comment]
I think we will just have to have it as another line below the names. Not directly below it, but with a slight gap

**Comment by joshdevous** [comment]
I believe there is direct support for localised timestamps in footers of embeds, no? Rather than just setting the footer normally. The first link I could find that sheds light on it is [this](https://birdie0.github.io/discord-webhooks-guide/structure/embed/timestamp.html).

@Zcamt might be worth looking into for #19

**Comment by Zcamt** [comment]
> I believe there is direct support for localised timestamps in footers of embeds, no? Rather than just setting the footer normally. The first link I could find that sheds light on it is [this](https://birdie0.github.io/discord-webhooks-guide/structure/embed/timestamp.html).
> 
> @Zcamt might be worth looking into for #19

It's not possible to add the "Last updated" before the timestamp, instead it'll say "Today at 02:44" and then update to 02:45 and so on whenever the leaderboard is updated, and be localised at the same time. 

Would look like this:
![image](https://user-images.githubusercontent.com/37076791/207753235-cad308ab-fefd-4ab3-abf6-c22557c51b8f.png)

**Comment by sttephen** [comment]
This works for me!

>

**Comment by joshdevous** [comment]
Yeah, I think that's the cleanest solution imo

**Comment by Zcamt** [comment]
Fixed in #19
