### ISSUE TITLE
[Enhancement]: Ability to list your recent rep

### ISSUE THREAD

**Issue by MLGPenguin** [learnspigot/discord-bot#91]
### Explain your idea.

Basically similar to how /rep shows your most recent 3 rep, a command which shows your previous 10, maybe with back and forward buttons to go 10-20, 20-30 and so on. so you can view all your rep, who gave it to you, and the channel name, etc.

Similar to the existing rep command;
![image](https://user-images.githubusercontent.com/72254337/209895729-9fb28cf7-62c9-4d8b-bfcd-370faf6c557f.png)

**Comment by Nuckerr** [comment]
We could just paginate the rep command
