### ISSUE TITLE
[Bug]: Add lookup does not work

### ISSUE THREAD

**Issue by Nuckerr** [learnspigot/discord-bot#94]
### Explain the issue.

Add lookup produces this error
http://paste.learnspigot.com/puyanonusi

### How to recreate?

Run /addlookup in any channel

### Anything else?

This issue persists after updating from master and restarting the bot (on prod)

**Comment by sttephen** [comment]
Wtf is /addlookup?

**Comment by Nuckerr** [comment]
The embed to lookup people's rep in #leaderboard

**Comment by sttephen** [comment]
Ahhh makes sense, thank you, command was removed in favour of people just not being idiots and deleting it. Surely we can rely on that from the team................................ right?
