### ISSUE TITLE
Send user DM on join

### ISSUE THREAD

**Issue by sttephen** [learnspigot/discord-bot#98]
User should receive a DM on first join. If you choose to do this pr, please create EXACTLY what is below. Emojis, capitals, everything. Cheers!

![image](https://user-images.githubusercontent.com/35041891/210440919-424e421c-7e57-452e-8aa1-3aafbe2f8add.png)

**Comment by sttephen** [comment]
(Without the slash on the paste link, my bad)

**Comment by Zcamt** [comment]
> EXACTLY what is below. Emojis, capitals, everything. Cheers!

Sir yes sir
